### ISSUE TITLE
Dead link on vninja.net

### ISSUE THREAD

**Issue by iootaa** [h0bbel/h0bbel#1]
Hi there,

[A page on your blog]( https://vninja.net/2020/02/12/my-hugo-workflow/) contains a link pointing to "a few custom Hugo shortcodes for Bootstrap4". This link is 404

(not sure of the right place to reach you as I don't use Twitter anymore)

Cheers

**Comment by h0bbel** [comment]
Seems to work for me, probably just a blip. Thanks for reporting though.

**Comment by iaeiou** [comment]
The issue is still there, 404 on "a few custom Hugo shortcodes for Bootstrap4"

**Comment by h0bbel** [comment]
Aha, that's because my source code is now in a private repository (no wonder it worked for me).

**Comment by h0bbel** [comment]
Fixed now.
